INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (1, 'Hotel California');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (2, 'Dark Side of the Moon');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (3, 'Abbey Road');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (4, 'Back in Black');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (5, 'Born to Run');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (6, 'Rumours');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (7, 'The Wall');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (8, 'Nevermind');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (9, 'Thriller');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (10, 'Led Zeppelin IV');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (11, 'The Joshua Tree');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (12, 'Purple Rain');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (13, 'London Calling');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (14, 'OK Computer');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (15, 'Kind of Blue');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (16, 'A Love Supreme');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (17, 'Pet Sounds');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (18, 'Blonde on Blonde');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (19, 'Wish You Were Here');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (20, 'Sticky Fingers');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (21, 'Let It Be');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (22, 'The Rise and Fall of Ziggy Stardust');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (23, 'Appetite for Destruction');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (24, 'Sgt Peppers Lonely Hearts Club Band');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (25, 'Master of Puppets');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (26, 'The Chronic');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (27, 'Ready to Die');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (28, 'Illmatic');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (29, 'Enter the Wu-Tang');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (30, 'Aquemini');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (31, 'My Beautiful Dark Twisted Fantasy');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (32, 'To Pimp a Butterfly');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (33, 'Channel Orange');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (34, 'In Rainbows');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (35, 'Kid A');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (36, 'Loveless');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (37, 'Disintegration');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (38, 'Remain in Light');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (39, 'Unknown Pleasures');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (40, 'Parallel Lines');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (41, 'Blue Train');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (42, 'Bitches Brew');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (43, 'The Miseducation of Lauryn Hill');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (44, 'Hounds of Love');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (45, 'Homogenic');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (46, 'Blue');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (47, 'Tapestry');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (48, 'Songs in the Key of Life');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (49, 'Innervisions');
INSERT INTO AlbumsNgramMin1 (AlbumId, Title) VALUES (50, 'Graceland');

INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (1, 'Hotel California');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (2, 'Dark Side of the Moon');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (3, 'Abbey Road');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (4, 'Back in Black');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (5, 'Born to Run');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (6, 'Rumours');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (7, 'The Wall');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (8, 'Nevermind');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (9, 'Thriller');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (10, 'Led Zeppelin IV');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (11, 'The Joshua Tree');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (12, 'Purple Rain');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (13, 'London Calling');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (14, 'OK Computer');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (15, 'Kind of Blue');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (16, 'A Love Supreme');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (17, 'Pet Sounds');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (18, 'Blonde on Blonde');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (19, 'Wish You Were Here');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (20, 'Sticky Fingers');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (21, 'Let It Be');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (22, 'The Rise and Fall of Ziggy Stardust');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (23, 'Appetite for Destruction');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (24, 'Sgt Peppers Lonely Hearts Club Band');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (25, 'Master of Puppets');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (26, 'The Chronic');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (27, 'Ready to Die');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (28, 'Illmatic');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (29, 'Enter the Wu-Tang');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (30, 'Aquemini');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (31, 'My Beautiful Dark Twisted Fantasy');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (32, 'To Pimp a Butterfly');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (33, 'Channel Orange');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (34, 'In Rainbows');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (35, 'Kid A');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (36, 'Loveless');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (37, 'Disintegration');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (38, 'Remain in Light');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (39, 'Unknown Pleasures');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (40, 'Parallel Lines');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (41, 'Blue Train');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (42, 'Bitches Brew');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (43, 'The Miseducation of Lauryn Hill');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (44, 'Hounds of Love');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (45, 'Homogenic');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (46, 'Blue');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (47, 'Tapestry');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (48, 'Songs in the Key of Life');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (49, 'Innervisions');
INSERT INTO AlbumsNgramMin2 (AlbumId, Title) VALUES (50, 'Graceland');
