version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
    depends_on:
      - pubsub-emulator
  pubsub-emulator:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
